### ISSUE TITLE
subprocess.CalledProcessError: Command 'pdfplumber --types char < ''empty_test.pdf'' > 'char_output_dir/'empty_test.pdf'_chars.csv'' returned non-zero exit status 1.

### ISSUE THREAD

**Issue by Faizan-Saifullah** [abhishekgautam101/pdf_bboxes#1]
on this command:

python pdf_bboxes.py --input 'empty_test.pdf' --output_format "img" --output_folder .'/results'

it returns:

The system cannot find the file specified.
Traceback (most recent call last):
  File "pdf_bboxes.py", line 32, in <module>
    char_filepath = extract_chars(filepath, char_filename)
  File "C:\Users\lenovo\Desktop\OCR-SiP\pdf_bboxes\helper.py", line 14, in extract_chars
    subp.check_call(pdfplumber_cmd, shell=True)
  File "C:\Users\lenovo\anaconda3\envs\TensorFlow_GPU_Test\lib\subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'pdfplumber --types char < ''empty_test.pdf'' > 'char_output_dir/'empty_test.pdf'_chars.csv'' returned non-zero exit status 1.

**Comment by getabhishekified** [comment]
Hi @Faizan-Saifullah , this repo works only on Ubuntu as of now. As I can see you are running it on a Windows machine, pdfplumber will throw errors.
For now, try running on a Ubuntu Virtual Machine, in future I will add support for windows and mac also. 
Thanks.

**Comment by Faizan-Saifullah** [comment]
Thanks Abhishek. The problem was resolved.
